name: Yocto Files Sync

on:
  push:
    paths:
      - '**/*.bb'
      - '**/*.bbappend'
      - '**/*.conf'
      - '**/layer.conf'
      - '**/*.inc'
      - '**/*.bbclass'

jobs:
  sync-yocto-files:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Determine Yocto files list
        id: yocto
        run: |
          BEFORE=${{ github.event.before }}
          AFTER=${{ github.sha }}

          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            # True first run: list all Yocto files
            FILES=$(git ls-files | grep -E '\.(bb|bbappend|conf|inc|bbclass)$' || true)
            echo "mode=full" >> $GITHUB_OUTPUT
          else
            # Subsequent runs: only changed files
            CHANGED=$(git diff --name-only "$BEFORE" "$AFTER" \
              | grep -E '\.(bb|bbappend|conf|inc|bbclass)$' 2>/dev/null) || true
            if [ -z "$CHANGED" ]; then
              FILES=$(git ls-files | grep -E '\.(bb|bbappend|conf|inc|bbclass)$' || true)
              echo "mode=full" >> $GITHUB_OUTPUT
            else
              FILES="$CHANGED"
              echo "mode=incremental" >> $GITHUB_OUTPUT
            fi
          fi

          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Upload Yocto files to MinIO
        if: steps.yocto.outputs.files != ''
        run: |
          for f in ${{ steps.yocto.outputs.files }}; do
            DEST="test1/yocto-files/$(dirname "$f")"
            mc --insecure mb --ignore-existing local/${DEST}
            mc --insecure cp "$f" "local/${DEST}/"
          done


      - name: Done
        run: |
          echo "Upload complete (mode=${{ steps.yocto.outputs.mode }})."
