name: Yocto Files Sync

on:
  push:
    paths:
      - '**/*.bb'
      - '**/*.bbappend'
      - '**/*.conf'
      - '**/layer.conf'
      - '**/*.inc'
      - '**/*.bbclass'

jobs:
  sync-yocto-files:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine changed Yocto files
        id: changes
        run: |
          BEFORE=${{ github.event.before }}
          AFTER=${{ github.sha }}
          if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
            # First run: list all Yocto files
            CHANGED=$(git ls-files | grep -E '\.(bb|bbappend|conf|inc|bbclass)$' || true)
          else
            CHANGED=$(git diff --name-only "$BEFORE" "$AFTER" \
              | grep -E '\.(bb|bbappend|conf|inc|bbclass)$' || true)
          fi
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      - name: Upload changed files to MinIO
        if: steps.changes.outputs.files != ''
        run: |
          for f in ${{ steps.changes.outputs.files }}; do
            DEST="test1/yocto-files/$(dirname "$f")"
            mc mb --ignore-existing local/${DEST}
            mc cp "$f" "local/${DEST}/"
          done
